new todo-frontend
RedHatTraining/DO288-apps pull request #135
Opened 2021-05-19 17:22 UTC by gjbianco

2021-05-20 15:31 UTC, rsriniva requested changes
All good. app should be tested on Node.js version on classroom workstation VM. Check with richard to see what rpm version in our repos is- I suspect 10.x. All node.js labs should consistently use the same node/npm version - preferably latest LTS v14?

2021-05-20 15:31 UTC, rsriniva commented on todo-frontend/Dockerfile
> -FROM registry.access.redhat.com/ubi8:8.0
Think we need a Dockerfile/Containerfile for the FE container

2021-06-15 13:57 UTC, rsriniva approved these changes
Approved. Merge. I will QA when complete lab is ready

2021-06-15 14:42 UTC, merged

2021-06-15 15:35 UTC, richardallred commented
should this have gone into `main`?